### PR TITLE
add metadata

### PR DESCRIPTION
**Pull request by maelle**
:wave: @salvafern 

- is this what you meant?
- do the metadata requirements/docs live elsewhere that I could link to instead of linking to https://github.com/EMODnet/seadog/blob/metadata/inst/metadata-template.md?

### CODE REVIEW

**Comment by salvafern** [comment]
Hi! 

Well I was thinking more about adding extra checks to [author-checklist.md](https://github.com/EMODnet/seadog/blob/metadata/inst/author-checklist.md) or to [reviewer-checklist.md](https://github.com/EMODnet/seadog/blob/metadata/inst/reviewer-checklist.md). 

Except the two last questions that are specific for the data products, 
> What datasets does this product uses? List the IMIS dasids, and/or DOIs from datasets not listed in IMIS
> Is this product a continuation of an older product? Does it uses another product? - If yes, please provide its IMIS dasid.

all the other bullet points are mandatory for IMIS.

There is some info online containing the metadata required, for instance:
* The EMODnet-Biology submission form: https://www.emodnet-biology.eu/contribute
* The EMODnet Ingestion submission system: https://submission.emodnet-ingestion.eu/
* This guide (slide 4): https://www.emodnet-biology.eu/sites/emodnet-biology.eu/files/public/tutorials/Guidance_How_to_share_biodiversity_data.pdf

I'm open to suggestions!

**Comment by maelle** [comment]
Thank you @salvafern! I've updated the PR. See also #17 and #18 for "live" examples. Is this more in line with what you had in mind?

**Comment by annakrystalli** [comment]
Sorry to be late to the party! 

Just wanted to note that a lot of the info that is asked to be documented in the README is actually collected as part of `dataspice` metadata.

In some ways we are asking folks to duplicate their metadata documentation effort while including that info as text in the README (if they picked only one option) makes it non machine readable. 

Is this ideal?

If that info is in the dataspice.json metadata, it can easily be presented in the README programmatically, or even better through the the html page that `dataspice` can produce.

What do you think @salvafern

**Comment by annakrystalli** [comment]
Actually the taxonomic aspect is not part of dataspice standard. Really it seems we are asking for all the info of the EML standard.

🤔 Not sure what to suggest.

**Comment by maelle** [comment]
Should your dataspice tutorial show a way to transform the JSON into text for a README for instance? :thinking: 

Reg the jump to EML, maybe it could be a next step (in people's learning journey).

**Comment by annakrystalli** [comment]
> Should your dataspice tutorial show a way to transform the JSON into text for a README for instance? 🤔

Sure. OK, to bolster what you can do with the `.json` metadata I will show:
- how you can read it in and print some of the info in the README
- even better how you can create an `index.html` version of the metadata which you can serve through gh-pages

**Comment by annakrystalli** [comment]
> Reg the jump to EML, maybe it could be a next step (in people's learning journey).

Agreed. The only reason I ask is because @salvafern would like it collected but dataspice doesn't collect it. I actually think it would be more useful to ask them to include an additional `taxonomies.csv` which they should be able to easily write out from R.

**Comment by maelle** [comment]
Thank you! 

What do you think of [`de621e3` (#13)](https://github.com/EMODnet/seadog/pull/13/commits/de621e37b4d467468f8f9b1776c1578d838990ec)

**Review by annakrystalli — APPROVED** [review]
LGTM!

**Review by salvafern — APPROVED** [review]

**Comment by salvafern** [comment]
Well the taxonomy part is important but can be done also via keywords (e.g. polyphyletic groups), or just provide the higher taxonomic rank. It is not the intention to include all the species in the metadata, as in some products there were up to 4K species. If dataspice doesn't include taxonomy that would be still ok 😄

**Pull request merged**
